name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_365_SANBOX }}
        allow-no-subscriptions: true
       
    - name: Get Redirect URL's
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/806214f1-fd05-45db-9175-76e6890c1767' --query spa.redirectUris
          existing=$(az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/806214f1-fd05-45db-9175-76e6890c1767' --query spa.redirectUris)
          echo "Fetched URL's"
          echo $existing
          echo "Adding new URL"
          existing+=https://localhost:5000
          echo "${existing[@]}"
          echo "Updating URL's"
          az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/806214f1-fd05-45db-9175-76e6890c1767' --headers 'Content-Type=application/json' --body "{spa:{redirectUris:$existing}}"
    - name: Update Redirect URL's
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          #az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/806214f1-fd05-45db-9175-76e6890c1767' --headers 'Content-Type=application/json' --body "{spa:{redirectUris:['http://localhost:3000']}}"

            
