name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_365_SANBOX }}
        allow-no-subscriptions: true
       
    - name: Create Deployment Slot
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/806214f1-fd05-45db-9175-76e6890c1767' --query spa.redirectUris
            
            
